# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

fibonacciArray = [1, 2]
x = 0
sum = 0

# Build the Fibonacci Array as long as max term in array is less than 4000000

while fibonacciArray.max < 4000000

	nextNum = fibonacciArray[x] + fibonacciArray.last
	fibonacciArray << nextNum
	x = x + 1

end

# Delete off terms from array.

fibonacciArray.delete_if &:odd?

# Sum remaing even array elements and outp the total.

fibonacciArray.each { |element| sum += element}
puts "The total is " + sum.to_s + "."

	